---
name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: read-all
jobs:
  build:
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Build
        run: go build -v ./...
  test:
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
      - uses: brian-pickens/go-test-report@v1
        with:
          packages: "./..."
          summary: "true"
  coverage:
    permissions:
      contents: write
      checks: write
      issues: write
      pull-requests: write
      # To report GitHub Actions status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Set up Node.js (for coverage)
        uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: setup tsc
        run: npm install -g typescript
      - name: Gather dependencies
        run: go mod download
      - uses: gwatts/go-coverage-action@v2
        id: coverage
        with:
          coverage-threshold: 80
          cover-pkg: ./...
          ignore-pattern: |
            \.pb\.go$
            \_string\.go$
            \main\.go$
            \internal\/test\/.*$
      - name: Generate coverage tree map
        run: |
          go run github.com/nikolaydubina/go-cover-treemap@latest \
          -coverprofile ${{ steps.coverage.outputs.gocov-agg-pathname }} \
          -only-folders=true >/tmp/treemap.svg
      - uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageCommand: make coverage-report-ci
          prefix: github.com/NSXBet/batcher
          coverageLocations: |
            ${{github.workspace}}/coverage.txt:gocov
  lint:
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-linter
        uses: nsx-actions/super-linter_super-linter@v6.6.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
          VALIDATE_JSCPD: false
  go-action-detection:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.22.0"
      - name: Run snapshot action
        uses: actions/go-dependency-submission@v2
        with:
          go-mod-path: go.mod
