---
name: Report Card Reporting
on:
  push:
    branches: ["main"]
permissions: read-all
jobs:
  report-card:
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Go Report Card
        uses: nsx-actions/creekorful_goreportcard-action@v1.0
